config/routes.rb
Rails.application.routes.draw do

  resources :nutrition_items

  get 'supplement_usages/new'
  get 'supplement_usages/create'

  resources :supplements do
    get 'add_stack', to: 'users#add_supplement_to_stack'
    get 'nutrition', to: 'supplements#nutrition'
    post 'nutrition', to: 'supplements#create_nutrition'
  end
  resources :supplement_sub_categories
  resources :supplement_categories

  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    get 'supplements'
    get 'supplements/new', to: 'users#add_supplements', as: 'new_supplements'
  end

  resources :night_entries
  get '/night_entries/new/:date', to: "night_entries#new", as: 'new_night_entry_date'

  resources :day_entries
  get '/day_entries/new/:date', to: "day_entries#new", as: 'new_day_entry_date'

  get 'journal', to: "journals#show"

  root 'home#index'
end

app/models/nutrition_item.rb
class NutritionItem < ActiveRecord::Base
  has_many :nutrition_infos
  has_many :supplements, through: :nutrition_infos

end

app/controllers/nutrition_items_controller.rb
class NutritionItemsController < ApplicationController
  before_action :set_nutrition_item, only: [:show, :edit, :update, :destroy]

  # GET /nutrition_items
  # GET /nutrition_items.json
  def index
    @nutrition_items = NutritionItem.all
  end

  # GET /nutrition_items/1
  # GET /nutrition_items/1.json
  def show
  end

  # GET /nutrition_items/new
  def new
    @nutrition_item = NutritionItem.new
  end

  # GET /nutrition_items/1/edit
  def edit
  end

  # POST /nutrition_items
  # POST /nutrition_items.json
  def create
    @nutrition_item = NutritionItem.new(nutrition_item_params)

    respond_to do |format|
      if @nutrition_item.save
        format.html { redirect_to @nutrition_item, notice: 'Nutrition item was successfully created.' }
        format.json { render :show, status: :created, location: @nutrition_item }
      else
        format.html { render :new }
        format.json { render json: @nutrition_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nutrition_items/1
  # PATCH/PUT /nutrition_items/1.json
  def update
    respond_to do |format|
      if @nutrition_item.update(nutrition_item_params)
        format.html { redirect_to @nutrition_item, notice: 'Nutrition item was successfully updated.' }
        format.json { render :show, status: :ok, location: @nutrition_item }
      else
        format.html { render :edit }
        format.json { render json: @nutrition_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nutrition_items/1
  # DELETE /nutrition_items/1.json
  def destroy
    @nutrition_item.destroy
    respond_to do |format|
      format.html { redirect_to nutrition_items_url, notice: 'Nutrition item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nutrition_item
      @nutrition_item = NutritionItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nutrition_item_params
      params.require(:nutrition_item).permit(:name, :unit_of_measure)
    end
end

app/helpers/nutrition_items_helper.rb
module NutritionItemsHelper
end

app/views/nutrition_items/_form.html.erb
<%= form_for @nutrition_item do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label' %>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :unit_of_measure, :class => 'control-label' %>
    <%= f.text_field :unit_of_measure, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                nutrition_items_path, :class => 'btn' %>
  </div>
<% end %>

app/views/nutrition_items/edit.html.erb
<%- model_class = NutritionItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nutrition_items/index.html.erb
<%- model_class = NutritionItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:unit_of_measure) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @nutrition_items.each do |nutrition_item| %>
      <tr>
        <td><%= link_to nutrition_item.name, nutrition_item_path(nutrition_item) %></td>
        <td><%= nutrition_item.unit_of_measure %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_nutrition_item_path(nutrition_item), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      nutrition_item_path(nutrition_item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_nutrition_item_path,
            :class => 'btn btn-primary' %>

app/views/nutrition_items/new.html.erb
<%- model_class = NutritionItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nutrition_items/show.html.erb
<%- model_class = NutritionItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @nutrition_item.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unit_of_measure) %>:</strong></dt>
  <dd><%= @nutrition_item.unit_of_measure %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              nutrition_items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_nutrition_item_path(@nutrition_item), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              nutrition_item_path(@nutrition_item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>