config/routes.rb
Rails.application.routes.draw do

  resources :nutrition_items

  get 'supplement_usages/new'
  get 'supplement_usages/create'

  resources :supplements do
    get 'add_stack', to: 'users#add_supplement_to_stack'
    get 'nutrition', to: 'supplements#nutrition'
    post 'nutrition', to: 'supplements#create_nutrition'
  end
  resources :supplement_sub_categories
  resources :supplement_categories

  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    get 'supplements'
    get 'supplements/new', to: 'users#add_supplements', as: 'new_supplements'
  end

  resources :night_entries
  get '/night_entries/new/:date', to: "night_entries#new", as: 'new_night_entry_date'

  resources :day_entries
  get '/day_entries/new/:date', to: "day_entries#new", as: 'new_day_entry_date'

  get 'journal', to: "journals#show"

  root 'home#index'
end

app/models/day_entry.rb
class DayEntry < ActiveRecord::Base
  belongs_to :journal
  validates :journal_id, presence: true

  def self.entries_this_month user
    # DayEntry.where("extract(month from created_at) = ?", Date.today.month) SQL
    user.journal.day_entries.where("strftime('%Y%m', created_at) = ?", Date.today.strftime('%Y%m'))
  end

  def self.this_day(date, user)
    # DayEntry.where("strftime('%Y%m%d', created_at) = ?", date.strftime('%Y%m%d'))
    user.journal.day_entries.where(entry_date: date).first
  end

  def self.today user
    user.journal.day_entries.where(entry_date: Date.today).first
  end

  def sleep_time
    "#{minutes_of_sleep/60}:#{minutes_of_sleep%60}" if minutes_of_sleep
  end
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :user
  has_many :day_entries
  has_many :night_entries

  def set_day_entry day_entry_id
    current_day_entry_id = day_entry_id if DayEntry.find(day_entry_id).entry_date == Date.today
  end

  def set_night_entry night_entry_id
    current_night_entry_id = night_entry_id if NightEntry.find(night_entry_id).entry_date == Date.today
  end

end

app/models/night_entry.rb
class NightEntry < ActiveRecord::Base
  belongs_to :journal
  validates :journal_id, presence: true

  def self.entries_this_month user
    # DayEntry.where("extract(month from created_at) = ?", Date.today.month) SQL
    user.journal.night_entries.where("strftime('%Y%m', created_at) = ?", Date.today.strftime('%Y%m'))
  end

  def self.this_day(date, user)
    # DayEntry.where("strftime('%Y%m%d', created_at) = ?", date.strftime('%Y%m%d'))
    user.journal.night_entries.where(entry_date: date).first
  end

  def self.today user
    user.journal.night_entries.where(entry_date: Date.today).first
  end

end

app/models/nutrition_info.rb
class NutritionInfo < ActiveRecord::Base
  belongs_to :supplement
  belongs_to :nutrition_item
end

app/models/nutrition_item.rb
class NutritionItem < ActiveRecord::Base
  has_many :nutrition_infos
  has_many :supplements, through: :nutrition_infos

end

app/models/supplement.rb
class Supplement < ActiveRecord::Base
  belongs_to :supplement_category
  belongs_to :supplement_sub_category

  has_many :supplement_usages
  has_many :users, through: :supplement_usages

  has_many :nutrition_infos
  has_many :supplement_items, through: :nutrition_infos

  validates_presence_of :brand
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/supplement_category.rb
class SupplementCategory < ActiveRecord::Base
  has_many :supplement_sub_categories
  has_many :supplements
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/supplement_sub_category.rb
class SupplementSubCategory < ActiveRecord::Base
  belongs_to :supplement_category
  has_many :supplements

  validates_presence_of :name
  validates_presence_of :supplement_category
  validates_uniqueness_of :name
end

app/models/supplement_usage.rb
class SupplementUsage < ActiveRecord::Base
  belongs_to :user
  belongs_to :supplement
  before_create :set_servings

private
  def set_servings
    self.remaining_servings = supplement.servings if supplement.servings
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :journal
  has_many :supplement_usages
  has_many :supplements, through: :supplement_usages

  # Gender ISO https://en.wikipedia.org/wiki/ISO/IEC_5218

  def get_journal
    if self.journal.nil?
      journal = Journal.new
      journal.user = self
      journal.save
    end
    return self.journal
  end

  def today_entry
    DayEntry.today self
  end

  def this_month_day_entries
    DayEntry.entries_this_month self
  end

  def this_day_entry date
    DayEntry.this_day(date, self)
  end

  def tonight_entry
    NightEntry.today self
  end

  def this_month_night_entries
    NightEntry.entries_this_month self
  end

  def this_night_entry date
    NightEntry.this_day(date, self)
  end

  def current_weight
    journal.day_entries.order('entry_date DESC').limit(1).first.weight
  end

  def first_weight
    journal.day_entries.order('entry_date').limit(1).first.weight
  end

  def current_bf
    journal.day_entries.order('entry_date DESC').limit(1).first.bodyfat
  end

  def first_bf
    journal.day_entries.order('entry_date').limit(1).first.bodyfat
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'paper'
  before_action :authenticate_user!
  before_action :get_journal

  # Uncomnet this method and the before action if there is no journal entry in the DB
  def get_journal
    current_user.get_journal unless current_user.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  def show
    @day_entries = current_user.this_month_day_entries
    @night_entries = current_user.this_month_night_entries
    @weight = "Weight: #{current_user.current_weight} (#{(current_user.current_weight-current_user.first_weight).round(2)})"
    @bodyfat = "Bodyfat: #{current_user.current_bf}% (#{(current_user.current_bf-current_user.first_bf).round(2)}%)"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :supplements, :add_supplements]

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def supplements
    @user = User.find(params[:user_id])
    @supplements = @user.supplement_usages
  end

  def add_supplements
    @supplements = Supplement.all
  end

  def add_supplement_to_stack
    @supplement = Supplement.find(params[:supplement_id])
    @stack = SupplementUsage.new(user: current_user, supplement: @supplement, start_date: Date.today)

    respond_to do |format|
      if @stack.save
        format.html { redirect_to user_supplements_path(current_user), notice: 'Supplement added to your stack!' }
      else
        format.html { redirect_to user_new_supplements_path(current_user), notice: 'could not save' }
        format.json { render json: @stack.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_user
      if params[:user_id]
        @user = User.find(params[:user_id])
      else
        @user = User.find(params[:id])
      end
    end

    def user_params
      params.require(:user).permit(:username, :dob, :height, :sex, :activity_level)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/day_entries_helper.rb
module DayEntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/night_entries_helper.rb
module NightEntriesHelper
end

app/helpers/nutrition_items_helper.rb
module NutritionItemsHelper
end

app/helpers/supplement_usages_helper.rb
module SupplementUsagesHelper
end

app/helpers/supplements_helper.rb
module SupplementsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/journals/show.html.erb
<%- model_class = Journal -%>

<%= "Current #{@weight}" %><br />
<%= "Current #{@bodyfat}" %>


<div class="page-header">
  <h2><%= Date.today.strftime("%B") %> Entries</h2>
</div>


<%= month_calendar do |date| %>
  <%= date.day %> <br />
  <% if current_user.this_day_entry(date) %>
    <%= link_to "✅ Day", day_entry_path(current_user.this_day_entry(date)) %>
  <% else %>
    <%= link_to "Add day", new_day_entry_date_path(date) %>
  <% end %>
  <br />
  <% if current_user.this_night_entry(date) %>
    <%= link_to "✅ Night", night_entry_path(current_user.this_night_entry(date)) %>
  <% else %>
    <%= link_to "Add night", new_night_entry_date_path(date) %>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :username, :class => 'control-label' %>
    <%= f.text_field :username, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :dob, :class => 'control-label' %>:
    <%= f.date_select :dob, :class => 'datepicker' %>
  </div>
  <div class="form-group">
    <%= f.label :height, :class => 'control-label' %> in centimeters:
    <%= f.number_field :height, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :sex, :class => 'control-label' %>
    <%= f.number_field :sex, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :activity_level, :class => 'control-label' %>
    <%= f.number_field :activity_level, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_path(current_user), :class => 'btn' %>
    <%= link_to 'Account settings', edit_user_registration_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/_supplements.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th>Category</th>
      <th>Sub-category</th>
      <th>Servings</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @supplements.each do |supplement| %>
      <tr>
        <td><%= link_to supplement.name, supplement_path(supplement) %></td>
        <td><%= supplement.brand %></td>
        <td><%= link_to supplement.supplement_category.name, supplement_category_path(supplement.supplement_category) %></td>
        <td><%= link_to supplement.supplement_sub_category.name, supplement_sub_category_path(supplement.supplement_sub_category) %></td>
        <td><%= supplement.servings %></td>
        <td>
          <%= link_to 'Add to stack', supplement_add_stack_path(supplement), :class => 'btn btn-primary btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/add_supplements.html.erb
<div class="page-header">
  <h3>Add a new supplement to your stack!</h3>
</div>

<%= render 'supplements' %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_supplement_path,
            :class => 'btn btn-primary' %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <% if @user.username.empty? %>
    <h2><%= @user.email %></h2>
  <% else %>
    <h2><%= @user.username.capitalize %></h2>
  <% end %>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @user.username %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dob) %>:</strong></dt>
  <dd><%= @user.dob %></dd>
  <dt><strong><%= model_class.human_attribute_name(:height) %>:</strong></dt>
  <dd><%= @user.height %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sex) %>:</strong></dt>
  <dd><%= @user.sex %></dd>
  <dt><strong><%= model_class.human_attribute_name(:activity_level) %>:</strong></dt>
  <dd><%= @user.activity_level %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-primary' %>
</div>

app/views/users/supplements.html.erb
<%- model_class = Supplement -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human %> Stack</h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:brand) %></th>
      <th><%= model_class.human_attribute_name(:supplement_sub_category_id) %></th>
      <th><%= model_class.human_attribute_name(:remaining_servings) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @supplements.each do |stack| %>
      <tr>
        <td><%= link_to stack.supplement.name, supplement_path(stack.supplement) %></td>
        <td><%= stack.supplement.brand %></td>
        <td><%= stack.supplement.supplement_sub_category.name %></td>
        <td><%= stack.remaining_servings %></td>
        <td><%=l stack.start_date %></td>
        <td>
        <!-- TODO -->
          <%= link_to 'Add',
                      edit_supplement_path(stack.supplement), :class => 'btn btn-primary btn-xs' %>
          <%= link_to 'Done',
                      supplement_path(stack.supplement),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add to your stack', user_new_supplements_path, :class => 'btn btn-primary' %>