config/routes.rb
Rails.application.routes.draw do

  resources :nutrition_items

  get 'supplement_usages/new'
  get 'supplement_usages/create'

  resources :supplements do
    get 'add_stack', to: 'users#add_supplement_to_stack'
    get 'nutrition', to: 'supplements#nutrition'
    post 'nutrition', to: 'supplements#create_nutrition'
  end
  resources :supplement_sub_categories
  resources :supplement_categories

  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    get 'supplements'
    get 'supplements/new', to: 'users#add_supplements', as: 'new_supplements'
  end

  resources :night_entries
  get '/night_entries/new/:date', to: "night_entries#new", as: 'new_night_entry_date'

  resources :day_entries
  get '/day_entries/new/:date', to: "day_entries#new", as: 'new_day_entry_date'

  get 'journal', to: "journals#show"

  root 'home#index'
end

app/models/day_entry.rb
class DayEntry < ActiveRecord::Base
  belongs_to :journal
  validates :journal_id, presence: true

  def self.entries_this_month user
    # DayEntry.where("extract(month from created_at) = ?", Date.today.month) SQL
    user.journal.day_entries.where("strftime('%Y%m', created_at) = ?", Date.today.strftime('%Y%m'))
  end

  def self.this_day(date, user)
    # DayEntry.where("strftime('%Y%m%d', created_at) = ?", date.strftime('%Y%m%d'))
    user.journal.day_entries.where(entry_date: date).first
  end

  def self.today user
    user.journal.day_entries.where(entry_date: Date.today).first
  end

  def sleep_time
    "#{minutes_of_sleep/60}:#{minutes_of_sleep%60}" if minutes_of_sleep
  end
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :user
  has_many :day_entries
  has_many :night_entries

  def set_day_entry day_entry_id
    current_day_entry_id = day_entry_id if DayEntry.find(day_entry_id).entry_date == Date.today
  end

  def set_night_entry night_entry_id
    current_night_entry_id = night_entry_id if NightEntry.find(night_entry_id).entry_date == Date.today
  end

end

app/models/night_entry.rb
class NightEntry < ActiveRecord::Base
  belongs_to :journal
  validates :journal_id, presence: true

  def self.entries_this_month user
    # DayEntry.where("extract(month from created_at) = ?", Date.today.month) SQL
    user.journal.night_entries.where("strftime('%Y%m', created_at) = ?", Date.today.strftime('%Y%m'))
  end

  def self.this_day(date, user)
    # DayEntry.where("strftime('%Y%m%d', created_at) = ?", date.strftime('%Y%m%d'))
    user.journal.night_entries.where(entry_date: date).first
  end

  def self.today user
    user.journal.night_entries.where(entry_date: Date.today).first
  end

end

app/models/nutrition_info.rb
class NutritionInfo < ActiveRecord::Base
  belongs_to :supplement
  belongs_to :nutrition_item
end

app/models/nutrition_item.rb
class NutritionItem < ActiveRecord::Base
  has_many :nutrition_infos
  has_many :supplements, through: :nutrition_infos

end

app/models/supplement.rb
class Supplement < ActiveRecord::Base
  belongs_to :supplement_category
  belongs_to :supplement_sub_category

  has_many :supplement_usages
  has_many :users, through: :supplement_usages

  has_many :nutrition_infos
  has_many :supplement_items, through: :nutrition_infos

  validates_presence_of :brand
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/supplement_category.rb
class SupplementCategory < ActiveRecord::Base
  has_many :supplement_sub_categories
  has_many :supplements
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/supplement_sub_category.rb
class SupplementSubCategory < ActiveRecord::Base
  belongs_to :supplement_category
  has_many :supplements

  validates_presence_of :name
  validates_presence_of :supplement_category
  validates_uniqueness_of :name
end

app/models/supplement_usage.rb
class SupplementUsage < ActiveRecord::Base
  belongs_to :user
  belongs_to :supplement
  before_create :set_servings

private
  def set_servings
    self.remaining_servings = supplement.servings if supplement.servings
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :journal
  has_many :supplement_usages
  has_many :supplements, through: :supplement_usages

  # Gender ISO https://en.wikipedia.org/wiki/ISO/IEC_5218

  def get_journal
    if self.journal.nil?
      journal = Journal.new
      journal.user = self
      journal.save
    end
    return self.journal
  end

  def today_entry
    DayEntry.today self
  end

  def this_month_day_entries
    DayEntry.entries_this_month self
  end

  def this_day_entry date
    DayEntry.this_day(date, self)
  end

  def tonight_entry
    NightEntry.today self
  end

  def this_month_night_entries
    NightEntry.entries_this_month self
  end

  def this_night_entry date
    NightEntry.this_day(date, self)
  end

  def current_weight
    journal.day_entries.order('entry_date DESC').limit(1).first.weight
  end

  def first_weight
    journal.day_entries.order('entry_date').limit(1).first.weight
  end

  def current_bf
    journal.day_entries.order('entry_date DESC').limit(1).first.bodyfat
  end

  def first_bf
    journal.day_entries.order('entry_date').limit(1).first.bodyfat
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :supplements, :add_supplements]

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def supplements
    @user = User.find(params[:user_id])
    @supplements = @user.supplement_usages
  end

  def add_supplements
    @supplements = Supplement.all
  end

  def add_supplement_to_stack
    @supplement = Supplement.find(params[:supplement_id])
    @stack = SupplementUsage.new(user: current_user, supplement: @supplement, start_date: Date.today)

    respond_to do |format|
      if @stack.save
        format.html { redirect_to user_supplements_path(current_user), notice: 'Supplement added to your stack!' }
      else
        format.html { redirect_to user_new_supplements_path(current_user), notice: 'could not save' }
        format.json { render json: @stack.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_user
      if params[:user_id]
        @user = User.find(params[:user_id])
      else
        @user = User.find(params[:id])
      end
    end

    def user_params
      params.require(:user).permit(:username, :dob, :height, :sex, :activity_level)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/day_entries_helper.rb
module DayEntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/night_entries_helper.rb
module NightEntriesHelper
end

app/helpers/nutrition_items_helper.rb
module NutritionItemsHelper
end

app/helpers/supplements_helper.rb
module SupplementsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/paper.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "fitbook" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "paper", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>
    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "FitBook", root_path, class:"navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "Home", user_path(current_user) %></li>
            <li><%= link_to 'SuppStack', user_supplements_path(current_user) %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li><%= link_to 'Supplements', supplements_path %></li>
          <% end %>
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Journal <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "#{Date.today.strftime("%B")} Entries", journal_path %></li>
                <li class="divider"></li>
              <% if current_user.today_entry.nil? %>
                <li><%= link_to "Add day entry", new_day_entry_path %></li>
              <% else %>
                <li><%= link_to "View day entry", day_entry_path(current_user.today_entry) %></li>
              <% end %>
              <% if current_user.tonight_entry.nil? %>
                <li><%= link_to "Add night entry", new_night_entry_path %></li>
              <% else %>
                <li><%= link_to "View night entry", night_entry_path(current_user.tonight_entry) %></li>
              <% end %>
              </ul>
            </li>
            <li><%= link_to "Sign out", destroy_user_session_path %></li>
          <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container" style="padding-top:70px">
      <%= yield %>
    </div> <!-- /container -->


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "paper" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>